### ISSUE TITLE
Works in Godot 4 alpha 14 but crashes Godot 4 alpha 15

### ISSUE THREAD

**Issue by frankhale** [nathanfranke/gdextension#1]
I'm able to run this example project in Godot 4 alpha 14 with no issues but when I open the project in 4 alpha 15 Godot crashes when opening the project. Have you seen this issue before?

**Comment by frankhale** [comment]
I noticed `godot-cpp` was checked out to a specific commit so I just switched it to the main branch and used the latest changes there. The demo project is now working fine inside Godot 4 Alpha 15.

**Comment by nathanfranke** [comment]
Thanks for the report, yes we need to keep godot-cpp up to date, i will do this ASAP. I'm also going to look into using master instead of a commit hash.

**Comment by nathanfranke** [comment]
Should be fixed, will re-open if problem continues

**Comment by frankhale** [comment]
Thanks for the quick response!!!
