### ISSUE TITLE
Compiles for Godot4.4, not 4.3

### ISSUE THREAD

**Issue by nikotte** [nathanfranke/gdextension#11]
This GDextension compiles, in contrast to the official one in the Godot documentation, great ! However while it is stated to be for Godot 4.3, it demands Godot 4.4 on start  ( "... Cannot load a GDExtension built for Godot 4.4.0 using an older version of Godot (4.3.0)").
Could introducing branches for the various versions of Godot be an option, so each user can pull the template as required ?

**Comment by nathanfranke** [comment]
This should be fixed as of fdbd83574dc5adbbfff3af03d21aa12ae3ddf5b0. Thanks for reporting.

**Comment by jomiq** [comment]
Just a headsup if this is somehow an upstream issue:
I had this problem today when setting up (for windows/mingw build). The solution was just switching the submodule to the correct branch, adding a hint in the readme would suffice.
