### ISSUE TITLE
Unable to compile with 4.1.3 (probably anything since 4.1)

### ISSUE THREAD

**Issue by Squatnet** [nathanfranke/gdextension#7]
Attempting to compile for 4.1.3 (or probably anything since 4.1 wont work due to changes in the way `gdextension_init()` works in `register_types`

i'll fix it up and make a PR

**Comment by nathanfranke** [comment]
Mostly fixed in https://github.com/nathanfranke/gdextension/pull/8

I omitted your suggestion to have absolute paths in `example.gdextension`. It works fine for me with relative paths.

Working for me, Godot 4.2.1 on Linux.

**Comment by nathanfranke** [comment]
Should be working as of #8
